### ISSUE TITLE
 open output.txt: permission denied

### ISSUE THREAD

**Issue by demiscuzz** [dub-flow/sessionprobe#2]
running 'docker run -it --rm -v "$(pwd):/app/files" --name sessionprobe fw10/sessionprobe -u URLs' in kali as root I get:
2023/12/04 16:16:32 Progress: 98.39% (61/62 deduped URLs processed)
2023/12/04 16:16:32 Progress: 100.00% (62/62 deduped URLs processed)
2023/12/04 16:16:32 open output.txt: permission denied

**Comment by dub-flow** [comment]
Well, it sounds like you don't have permission to write the `output.txt` into the current working directory?

**Comment by demiscuzz** [comment]
I have tried running the command as root and with sudo, in a different directory, created a file called output.txt, same error.

**Comment by dub-flow** [comment]
I don't think this is an issue with `SessionProbe`. Can you try going into a directory like `/tmp` that should have very open permissions and see if that works?

**Comment by dub-flow** [comment]
@demiscuzz were you able to resolve the issue?
